"""General educational crop-health information for the 15 model labels."""
DISEASE_INFO = {
"Pepper__bell___Bacterial_spot": {"crop":"Bell pepper","disease":"Bacterial spot","symptoms":"Small water-soaked spots become dark or scab-like; yellowing and leaf drop may occur.","prevention":"Use clean seed and transplants, rotate away from pepper and tomato, sanitize tools, and avoid handling wet plants.","management":"Improve airflow and sanitation, avoid overhead irrigation, and consult local extension guidance for diagnosis and locally registered options."},
"Pepper__bell___healthy": {"crop":"Bell pepper","status":"Healthy","care":"Maintain even watering, suitable nutrition, good airflow, weed control, and routine inspection."},
"Potato___Early_blight": {"crop":"Potato","disease":"Early blight","symptoms":"Older leaves often show brown lesions with concentric rings and yellowing; severe infection can defoliate plants.","prevention":"Use healthy seed, rotate crops, remove volunteer potatoes and debris, and reduce prolonged leaf wetness.","management":"Maintain plant vigor and monitor lower leaves. Seek local extension advice for diagnosis and suitable options."},
"Potato___Late_blight": {"crop":"Potato","disease":"Late blight","symptoms":"Rapidly expanding water-soaked or dark lesions; humid conditions may show pale growth at lesion edges, and tubers can rot.","prevention":"Use certified seed, remove volunteer plants and cull piles, monitor local alerts, and limit leaf wetness.","management":"Spread can be rapid. Isolate affected material and contact local agricultural extension promptly for region-specific advice."},
"Potato___healthy": {"crop":"Potato","status":"Healthy","care":"Use healthy seed tubers, maintain even soil moisture, rotate crops, and inspect foliage and tubers regularly."},
"Tomato_Bacterial_spot": {"crop":"Tomato","disease":"Bacterial spot","symptoms":"Small dark water-soaked leaf spots, sometimes yellow-edged; fruit can develop raised scabby spots.","prevention":"Use clean seed and transplants, rotate crops, sanitize tools, and avoid wet foliage handling and overhead watering.","management":"Remove affected debris safely, reduce leaf wetness, and consult local extension guidance before considering locally approved controls."},
"Tomato_Early_blight": {"crop":"Tomato","disease":"Early blight","symptoms":"Brown target-like lesions usually begin on older leaves; yellowing and leaf drop may follow.","prevention":"Rotate crops, mulch against soil splash, water at the base, space plants, and remove diseased residues.","management":"Monitor lower foliage and maintain plant vigor. Confirm the cause and consult local extension guidance."},
"Tomato_Late_blight": {"crop":"Tomato","disease":"Late blight","symptoms":"Fast-growing irregular water-soaked lesions turn brown; humid weather may show pale growth at margins and fruit may rot.","prevention":"Use healthy transplants, remove volunteer hosts, improve airflow, limit leaf wetness, and follow local disease alerts.","management":"Act promptly because spread can be rapid. Keep suspect plants separate and contact local extension for confirmation."},
"Tomato_Leaf_Mold": {"crop":"Tomato","disease":"Leaf mold","symptoms":"Pale green or yellow patches above with olive-gray fuzzy growth beneath leaves, often in humid conditions.","prevention":"Increase spacing and ventilation, avoid wetting foliage, and reduce persistent greenhouse humidity.","management":"Remove badly affected leaves with clean tools and improve airflow. Seek local guidance if symptoms continue."},
"Tomato_Septoria_leaf_spot": {"crop":"Tomato","disease":"Septoria leaf spot","symptoms":"Many small circular spots with light centers and dark margins, often on lower leaves; yellowing and leaf drop may follow.","prevention":"Rotate crops, mulch against soil splash, water at the base, remove debris, and avoid working among wet plants.","management":"Remove affected lower leaves where practical and improve airflow. Ask local extension for confirmation and regional advice."},
"Tomato_Spider_mites_Two_spotted_spider_mite": {"crop":"Tomato","disease":"Two-spotted spider mite damage","symptoms":"Fine pale stippling or bronzing, possible fine webbing under leaves, and leaf drying in heavier infestations.","prevention":"Inspect leaf undersides, reduce dust and plant stress, and conserve beneficial insects.","management":"Confirm mites with close inspection. Use integrated pest management guidance and avoid unnecessary broad-spectrum treatments."},
"Tomato__Target_Spot": {"crop":"Tomato","disease":"Target spot","symptoms":"Brown circular leaf lesions may show concentric rings; spots can also occur on stems or fruit in warm humid conditions.","prevention":"Rotate crops, ensure spacing and airflow, clean up residues, and avoid prolonged leaf wetness.","management":"Remove severely affected material where practical, monitor spread, and seek local extension confirmation."},
"Tomato__Tomato_YellowLeaf__Curl_Virus": {"crop":"Tomato","disease":"Tomato yellow leaf curl virus","symptoms":"Leaves curl upward, yellow between veins, and become smaller; plants may be stunted with reduced fruit set.","prevention":"Use healthy transplants, manage whitefly vectors with local integrated methods, remove host weeds, and consider suitable resistant varieties.","management":"There is no curative treatment for infected plants. Confirm diagnosis, manage vectors responsibly, and ask extension services about affected plants."},
"Tomato__Tomato_mosaic_virus": {"crop":"Tomato","disease":"Tomato mosaic virus","symptoms":"Mottled light and dark green leaves, leaf distortion, and sometimes stunting or uneven fruit.","prevention":"Use clean seed and transplants, wash hands and sanitize tools, avoid tobacco contamination, and remove volunteer hosts.","management":"No curative treatment is available. Limit contact and tool-mediated spread, remove confirmed infected plants carefully, and seek extension advice."},
"Tomato_healthy": {"crop":"Tomato","status":"Healthy","care":"Provide consistent watering, suitable support and nutrition, airflow, and regular checks of leaf undersides, stems, and fruit."}
}
def get_disease_info(class_name: str):
    """Return curated information or None for an unknown model label."""
    return DISEASE_INFO.get(class_name)
